name: image2
description: This plugin simplifies the way to use all image types
version: 0.0.1

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  flutter_web_plugins:
    sdk: flutter
  regexpattern: ^2.0.1
  transparent_image: ^2.0.0
  video_thumbnail: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.tk.image2
        pluginClass: Image2Plugin
      ios:
        pluginClass: Image2Plugin
      windows:
        pluginClass: Image2Plugin
      web:
        pluginClass: Image2Web
        fileName: image2_web.dart
